name: to_do
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.0.1
  provider: ^6.1.2
  shared_preferences: ^2.3.0
  uuid: ^4.2.2
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.0.0

flutter:
  uses-material-design: true
